import Head from 'next/head';
import TopCards from '../components/TopCards';
import BarChart from '../components/BarChart';


export default function Home() {

    return (
        <>
            <Head>
                <title>Webserver</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className='bg-gray-100 min-h-screen dark:bg-dark dark:text-white'>
                <TopCards />
                <div className='p-4 grid md:grid-cols-3 grid-cols-1 gap-4 dark:bg-dark dark:text-white'>
                    <BarChart />
                </div>
            </main>
        </>
    );
}