import Head from 'next/head';
import TopCards from '../components/TopCards';
import BarChart from '../components/BarChart';
import { useEffect, useState } from 'react';
import Loader from '@/components/Loader';

export default function Home() {
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchData = async () => {
            try {
                await new Promise(resolve => setTimeout(resolve, 3000));


                setLoading(true);
            } catch (error) {
                setLoading(false);
            }
        };

        fetchData();
    }, []);

    return (
        <>
            <Head>
                <title>Webserver</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className='bg-gray-100 min-h-screen dark:bg-dark dark:text-white'>
                {loading ? (
                    <div className='flex items-center justify-center h-screen'>
                        <Loader />
                    </div>
                ) : (
                    <>
                        <TopCards />
                        <div className='p-4 grid md:grid-cols-3 grid-cols-1 gap-4 dark:bg-dark dark:text-white'>
                            <BarChart />
                        </div>
                    </>
                )}
            </main>
        </>
    );
}
