import Head from 'next/head';
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import TopCards from '../components/TopCards';
import BarChart from '../components/BarChart';
import { getSession, useSession, signOut } from "next-auth/react"

export default function Home() {

    const { data: session } = useSession()

    function handleSignOut() {
        signOut()
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className="bg-gray-100 min-h-screen dark:bg-dark dark:text-white">
                <TopCards />
                <div className="p-4 grid md:grid-cols-3 grid-cols-1 gap-4 dark:bg-dark dark:text-white">
                    <BarChart />
                </div>
            </main>

            {session ? User({ session, handleSignOut }) : Guest()}
        </div>
    )
}

export async function getServerSideProps({ req }) {
    const session = await getSession({ req })

    if (!session) {
        return {
            redirect: {
                destination: '/login',
                permanent: false
            }
        }
    }

    return {
        props: { session }
    }
}