import { getSession, useSession } from 'next-auth/react';
import { useEffect } from 'react';
import TopCards from '../components/TopCards';
import BarChart from '../components/BarChart';
import { useRouter } from 'next/router';

export default function Home() {
    const { data: session } = useSession();
    const router = useRouter();

    useEffect(() => {
        if (!session) {
            // Redirect to login page if the user is not authenticated
            router.push('/login');
        }
    }, [session, router]);

    if (!session) {
        return <div>Loading...</div>;
    }

    const handleLogout = async () => {
        await signOut({ redirect: false });
        router.push('/login');
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className='bg-gray-100 min-h-screen dark:bg-dark dark:text-white'>
                <TopCards />
                <div className='p-4 grid md:grid-cols-3 grid-cols-1 gap-4 dark:bg-dark dark:text-white'>
                    <BarChart />
                </div>

                {session && (
                    <button onClick={handleLogout} className='bg-gray-100 hover:bg-gray-200 cursor-pointer my-4 p-3 rounded-lg inline-block dark:bg-dark dark:text-white'>
                        <span>👤</span>
                        <h1 className='text-xs'>Logout</h1>
                    </button>
                )}
            </main>
        </>
    );
}

export async function getServerSideProps(context) {
    const session = await getSession(context);

    if (!session) {
        return {
            redirect: {
                destination: '/login',
                permanent: false,
            },
        };
    }

    return {
        props: {
            session,
        },
    };
}
